apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nixos-operator
  namespace: nixos-operator-system
  labels:
    app: nixos-operator
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: nixos-operator
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
  namespaceSelector:
    matchNames:
    - nixos-operator-system
