apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- machine-example.yaml
- ssh-key-secret.yaml
- ssh-private-key-secret.yaml

# Опционально: можно добавить генераторы для создания ресурсов
# generators:
# - ssh-key-generator.yaml
