apiVersion: nixos.infra/v1alpha1
kind: NixosConfiguration
metadata:
  name: worker-config
  namespace: default
spec:
  gitRepo: "https://github.com/your-org/nixos-configs.git"
  configurationPath: ".#worker"
  onRemoveConfigurationPath: ".#minimal"
  machineRef:
    name: worker-01
  fullInstall: false
  credentialsRef:
    name: git-credentials
  additionalFiles:
  - path: "secrets/wireguard-key"
    valueType: SecretRef
    secretRef:
      name: wireguard-secret
  - path: "config/custom.nix"
    valueType: Inline
    inline: |
      { config, pkgs, ... }:
      {
        services.nginx.enable = true;
      }
