apiVersion: v1
kind: Secret
metadata:
  name: ssh-public-key
  namespace: default
type: Opaque
stringData:
  ssh-publickey: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGWD3lRQNvGsjO12gv0+NPZbTZXgkYBPIZgJJTHGd08a flake-example-key
