name: Nightly Build

on:
  schedule:
    # Запускается каждый день в 2:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Позволяет запускать вручную

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Nightly Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for nightly
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          nightly
          type=raw,value=nightly-{{date 'YYYYMMDD'}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # integration-tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
  #   needs: build-and-push

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.11'
  #       cache: 'pip'

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install pytest pytest-asyncio

  #   - name: Set up Kind cluster
  #     uses: engineerd/setup-kind@v0.6.0
  #     with:
  #       version: "v0.20.0"

  #   - name: Run integration tests
  #     run: |
  #       # Здесь можно добавить интеграционные тесты с Kind
  #       echo "Running integration tests..."
  #       # kind create cluster --config kind-config.yaml
  #       # kubectl apply -f crds/
  #       # kubectl apply -f deployment.yaml
  #       # pytest tests/integration/ -v

  #   - name: Cleanup Kind cluster
  #     if: always()
  #     run: |
  #       kind delete cluster

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [build-and-push, integration-tests, security-scan]
    if: always()

    steps:
    - name: Notify on success
      if: needs.build-and-push.result == 'success' && needs.integration-tests.result == 'success'
      run: |
        echo "Nightly build completed successfully!"
        # Здесь можно добавить уведомления (Slack, Discord, etc.)

    - name: Notify on failure
      if: needs.build-and-push.result == 'failure' || needs.integration-tests.result == 'failure'
      run: |
        echo "Nightly build failed! Check the logs."
        # Здесь можно добавить уведомления об ошибках
