name: Nightly Build

on:
  schedule:
    # Runs every day at 2:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-containerfiles:
    name: Build All Container Images for Nightly
    uses: ./.github/workflows/build-containerfiles.yml
    with:
      tag_pattern: |
        nightly
        type=raw,value=nightly-{{date 'YYYYMMDD'}}
      push_images: true

  # integration-tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
  #   needs: build-and-push

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.11'
  #       cache: 'pip'

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install pytest pytest-asyncio

  #   - name: Set up Kind cluster
  #     uses: engineerd/setup-kind@v0.6.0
  #     with:
  #       version: "v0.20.0"

  #   - name: Run integration tests
  #     run: |
  #       # Add integration tests with Kind here
  #       echo "Running integration tests..."
  #       # kind create cluster --config kind-config.yaml
  #       # kubectl apply -f crds/
  #       # kubectl apply -f deployment.yaml
  #       # pytest tests/integration/ -v

  #   - name: Cleanup Kind cluster
  #     if: always()
  #     run: |
  #       kind delete cluster

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [build-containerfiles, security-scan]
    if: always()

    steps:
    - name: Notify on success
      if: needs.build-containerfiles.result == 'success' && needs.security-scan.result == 'success'
      run: |
        echo "Nightly build completed successfully!"
        # Add notifications here (Slack, Discord, etc.)

    - name: Notify on failure
      if: needs.build-containerfiles.result == 'failure' || needs.security-scan.result == 'failure'
      run: |
        echo "Nightly build failed! Check the logs."
        # Add failure notifications here
